### ISSUE TITLE
Could you help me with these?

### ISSUE THREAD

**Issue by SiddhantNaik17** [mikelxc/Workarounds-for-ARM-mac#1]
1) Are you able to install python 3.8 successfully?
2) Could you try installing Django 3.1 and check whether it can successfully start a server? It would be great if you could clone some OSS django project and check whether it runs without any issue.
3) Could you check whether Android studio installs and works properly? 
4) Whether you can connect android device via MTP

I want to confirm whether Django and Android Studio work properly because I don't think any tech youtuber would test these in their full reviews.

**Comment by mikelxc** [comment]
I was able to compile python 3.9 on my machine and get Django 3.1.3 running. I believe so long as the package is written is pure python, you would be able to do that without any trouble. 
For android studio, it runs with Rosetta2, just like other jetbrains IDEs.
I do not have any android devices available for testing. 
Hope this helps.

**Comment by SiddhantNaik17** [comment]
> I was able to compile python 3.9 on my machine and get Django 3.1.3 running. I believe so long as the package is written is pure python, you would be able to do that without any trouble. 
> For android studio, it runs with Rosetta2, just like other jetbrains IDEs.
> I do not have any android devices available for testing. 
> Hope this helps.
> 

That's great, thank you!

**Comment by mikelxc** [comment]
Updates, android studio itself is able to run without problem, and I'm ok to download all the sdks, but the simulator is barely usable and super laggy.
