### ISSUE TITLE
Can I link to your page?

### ISSUE THREAD

**Issue by mwidjaja1** [mikelxc/Workarounds-for-ARM-mac#2]
Not so much an issue but just wanted to say this guide is awesome! I've been sharing my notes to get a [Python Data Science stack up for ARM Macs](https://github.com/mwidjaja1/DSOnMacARM/blob/main/README.md) but your Xcode & Homebrew guidance smokes the pants off of mine. Could I link to yours?

Thanks!

**Comment by mikelxc** [comment]
Sure thing!

**Comment by mwidjaja1** [comment]
Awesome, thanks 🙂
