### ISSUE TITLE
Cannot install in Homebrew on Intel processor in ARM default prefix

### ISSUE THREAD

**Issue by AdamGerthel** [mikelxc/Workarounds-for-ARM-mac#7]
I followed your installation steps on a brand new Macbook Air M1 and got this error (after installation, moving and adding to path).

> Error: Cannot install in Homebrew on Intel processor in ARM default prefix (/opt/homebrew)!

When running `brew install -s pkg-config`

You listed that package as one of the packages you managed to install. Do you have any idea what could be missing from the instructions?

**Comment by mikelxc** [comment]
It seems that you are running the terminal in intel mode using Rosetta. You can check it by looking at activity monitor. Restart your terminal in arm mode will solve this issue.

**Comment by AdamGerthel** [comment]
@mikelxc That was the problem! Now moving on to the rest of the long list of issues using my new computer 😅
